- name: variables preference
  hosts: local
  connection: local
  # vars:
  #   NAME: this is from play level
  # vars_files:
  # #   - course.yaml
  # vars_prompt:
  # - name: NAME
  #   prompt: what is your username?
  #   private: false
  tasks:
  - name: course info
    # vars:
    #   NAME: this is from task level
    ansible.builtin.debug:
      msg: "hello ,the username is {{ NAME }},"


#PREFERENCES
#FROM COMMAND LINE
#FROM TASK LEVEL
#FROM FILES
#FROM PROMPT
#FROM PLAY LEVEL
#FROM INVENTORY