- name: loops
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: installing packages
    ansible.builtin.package:
      name: "{{ item }}"
      state: latest  #item keyword is reserved 
    loop:
    - nginx
    - zip
    - mysql