- name: error handling
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: check if user exists or not
    ansible.builtin.command: id roboshop
    register: user_output
    ignore_errors: true

  - name: print the output errors
    ansible.builtin.debug:
      msg: "{{ user_output }}"

  - name: print the output errors
    ansible.builtin.command: useradd roboshop
    when: user_output.rc != 0
